config/routes.rb
Rails.application.routes.draw do
  post "/enrollment_requests", to: "enrollments#enroll", as: "enrollment_requests"
  resources :enrollments, except: [:show, :new]
  resources :schools do
    resources :school_admins
    resources :courses, except: :index do
      resources :batches, except: :index
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "schools#index"
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :batch
  belongs_to :user
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_enrollment, only: %i[ show edit update destroy ]

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to school_course_batch_url(@enrollment.batch.course.school, 
          @enrollment.batch.course, @enrollment.batch), notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to school_course_batch_url(@enrollment.batch.course.school, 
          @enrollment.batch.course, @enrollment.batch), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def enroll
    @enrollment = Enrollment.new(batch_id: params["batch_id"], user_id: current_user.id)
    @enrollment.approval = false

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to school_course_batch_url(@enrollment.batch.course.school, 
          @enrollment.batch.course, @enrollment.batch), notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:batch_id, :user_id, :approval)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div id="<%= dom_id enrollment %>">
<p><strong>Batach Name:</strong><%= enrollment.batch.name%></p>
<p><strong>User to be approved:</strong><%= enrollment.user.email %>
</div>

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment) do |form| %>
  <% if enrollment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :batch_id, style: "display: block" %>
    <%= form.text_field :batch_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.collection_select :user_id, User.order(:email),:id, :email, include_blank: true %>
  </div>

  <div>
    <%= form.label :approval, style: "display: block" %>
    <%= form.check_box :approval %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Show this enrollment", @enrollment %> |
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/index.html.erb
<h1>Pending Enrollments</h1>

<div id="enrollments">
  <% @enrollments.where(approval: false).each do |enrollment| %>
    <%= render enrollment %>
    <p>
      <%= link_to "Approve enrollment", edit_enrollment_path(enrollment) %> |
      <%= button_to "Deny enrollment", enrollment_path(enrollment), method: :delete %>
    </p>
    <hr>
  <% end %>
</div>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @enrollment %>

<div>
  <%= link_to "Edit this enrollment", edit_enrollment_path(@enrollment) %> |
  <%= link_to "Back to enrollments", enrollments_path %>

  <%= button_to "Destroy this enrollment", @enrollment, method: :delete %>
</div>