config/routes.rb
Rails.application.routes.draw do
  post "/enrollment_requests", to: "enrollments#enroll", as: "enrollment_requests"
  resources :enrollments, except: [:show, :new]
  resources :schools do
    resources :school_admins
    resources :courses, except: :index do
      resources :batches, except: :index
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "schools#index"
end

app/models/school_admin.rb
class SchoolAdmin < ApplicationRecord
  belongs_to :school
  belongs_to :user
end

app/controllers/school_admins_controller.rb
class SchoolAdminsController < ApplicationController
  before_action :set_school_admin, only: %i[ show edit update destroy ]

  # GET /school_admins or /school_admins.json
  def index
    @school_admins = SchoolAdmin.all
  end

  # GET /school_admins/1 or /school_admins/1.json
  def show
  end

  # GET /school_admins/new
  def new
    school = School.find(params["school_id"])
    @school_admin = school.school_admins.new
  end

  # GET /school_admins/1/edit
  def edit
  end

  # POST /school_admins or /school_admins.json
  def create
    @school_admin = SchoolAdmin.new(school_admin_params)
    user = @school_admin.user
    user.role = "school_admin"
    respond_to do |format|
      if @school_admin.save && user.save
        format.html { redirect_to school_school_admins_url(@school_admin.school), notice: "School admin was successfully created." }
        format.json { render :show, status: :created, location: @school_admin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @school_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /school_admins/1 or /school_admins/1.json
  def update
    respond_to do |format|
      if @school_admin.update(school_admin_params)
        format.html { redirect_to school_school_admins_url(@school_admin.school), notice: "School admin was successfully updated." }
        format.json { render :show, status: :ok, location: @school_admin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @school_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_admins/1 or /school_admins/1.json
  def destroy
    @school_admin.destroy

    respond_to do |format|
      format.html { redirect_to schools_url, notice: "School admin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_admin
      @school_admin = SchoolAdmin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def school_admin_params
      params.permit(:school_id, :user_id)
    end
end

app/helpers/school_admins_helper.rb
module SchoolAdminsHelper
end

app/views/school_admins/_form.html.erb
<%= form_with(url: school_school_admins_path) do |form| %>
  <% if school_admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(school_admin.errors.count, "error") %> prohibited this school_admin from being saved:</h2>

      <ul>
        <% school_admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.collection_select :user_id, User.order(:email),:id, :email, include_blank: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/school_admins/_school_admin.html.erb
<div id="<%= dom_id school_admin %>">
<p>Email: <%= school_admin.user.email %></p>
</div>

app/views/school_admins/edit.html.erb
<h1>Editing school admin</h1>

<%= render "form", school_admin: @school_admin %>

<br>

<div>
  <%= link_to "Show this school admin", @school_admin %> |
  <%= link_to "Back to school admins", school_admins_path %>
</div>

app/views/school_admins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>School admins</h1>

<div id="school_admins">
  <% @school_admins.each do |school_admin| %>
    <%= render school_admin %>
    <p>
      <%= link_to "Show this school admin", school_school_admin_path(school_admin.school, school_admin) %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to "New school admin", new_school_school_admin_path %>

app/views/school_admins/new.html.erb
<h1>New school admin</h1>

<%= render "form", school_admin: @school_admin %>

<br>

<div>
  <%= link_to "Back", :back %>
</div>

app/views/school_admins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @school_admin %>

<div>
  <%= link_to "Edit this school admin", edit_school_school_admin_path(@school_admin.school, @school_admin) %> |
  <%= link_to "Back to school admins", school_school_admins_path(@school_admin.school) %>

  <%= button_to "Destroy this school admin", school_school_admin_path(@school_admin.school, @school_admin), method: :delete %>
</div>