config/routes.rb
Rails.application.routes.draw do
  post "/enrollment_requests", to: "enrollments#enroll", as: "enrollment_requests"
  resources :enrollments, except: [:show, :new]
  resources :schools do
    resources :school_admins
    resources :courses, except: :index do
      resources :batches, except: :index
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "schools#index"
end

app/models/school.rb
class School < ApplicationRecord
  has_many :school_admins, dependent: :destroy
  has_many :users, through: :school_admins
  has_many :courses, dependent: :destroy
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  load_and_authorize_resource
  before_action :set_school, only: %i[ show edit update destroy ]

  # GET /schools or /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1 or /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = Schools.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools or /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to school_url(@school), notice: "School was successfully created." }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1 or /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to school_url(@school), notice: "School was successfully updated." }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1 or /schools/1.json
  def destroy
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url, notice: "School was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def school_params
      params.require(:school).permit(:name, :description, :established_at)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school) do |form| %>
  <% if school.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% school.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :established_at, style: "display: block" %>
    <%= form.datetime_field :established_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/_school.html.erb
<div id="<%= dom_id school %>">
  <p>
    <strong>Name:</strong>
    <%= school.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= school.description %>
  </p>

  <p>
    <strong>Established at:</strong>
    <%= school.established_at %>
  </p>

</div>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render "form", school: @school %>

<br>

<div>
  <%= link_to "Show this school", @school %> |
  <%= link_to "Back to schools", schools_path %>
</div>

app/views/schools/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Schools</h1> 
  </div>
  <% if can? :manage, @schools %>
    <div class="col-md-4">
      <%= link_to "New school", new_school_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<div class="row">
  <% @schools.each do |school| %>
    <div class="col-md-3">
      <div id="<%= dom_id school %>" class="card" style="width: 18rem;">
        <img class="card-img-top" src="https://www.orchidsinternationalschool.com/wp-content/uploads/2022/09/Primary-School-scaled.jpg" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= school.name %></h5>
          <p class="card-text"><%= school.description %></p>
          <%= link_to "View", school, class: "btn btn-info" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render "form", school: @school %>

<br>

<div>
  <%= link_to "Back to schools", schools_path %>
</div>

app/views/schools/show.html.erb
<div class="row">
  <div class="col-md-4">
    <img src="https://www.orchidsinternationalschool.com/wp-content/uploads/2022/09/Primary-School-scaled.jpg" class="img-fluid rounded mx-auto d-block" alt="...">
    <h3><%= @school.name %></h3>
    <p><strong>Established on</strong> <%= @school.established_at %></p>
    <p><%= @school.description %></p>
      <% if can? :update, @school %>
        <div>
          <%= link_to "Edit this school", edit_school_path(@school) %> |
          <%= link_to "Back to schools", schools_path %>
          </br>
          <% if can? :destory, @school %>
            <%= button_to "Delete this school", @school, method: :delete %>
          <% end %>
        </div>
      <% end %>

      <% if can? :manage, @school %>
        <%= link_to "School Admins", school_school_admins_path(@school) %>
      <% end %>
  </div>
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-10">
        <h4>Courses</h4> 
      </div>
        <% if can? :update, @school %>
          <div class="col-md-2">
            <%= link_to "New course", new_school_course_path(@school), class: "btn btn-primary" %>
          </div>
        <% end %>
    </div><br>
    <div class="row">
      <% @school.courses.each do |course| %>
        <div class="col-md-4">
          <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="https://i.ytimg.com/vi/cS8lqPqXSlM/maxresdefault.jpg" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title"><%= course.title %></h5>
              <p class="card-text"><%= course.description %></p>
              <%= link_to "View", school_course_path(@school, course), class: "btn btn-info" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>