config/routes.rb
Rails.application.routes.draw do
  post "/enrollment_requests", to: "enrollments#enroll", as: "enrollment_requests"
  resources :enrollments, except: [:show, :new]
  resources :schools do
    resources :school_admins
    resources :courses, except: :index do
      resources :batches, except: :index
    end
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "schools#index"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  load_and_authorize_resource
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    school = School.find(params["school_id"])
    @course = school.courses.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to school_course_url(@course.school_id, @course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to school_course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to school_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.permit(:title, :description, :school_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>">
  <img src="https://b2227390.smushcdn.com/2227390/wp-content/themes/alexander/assets/img/headers/header-course-delivery.jpg?lossy=1&strip=1&webp=1" class="img-fluid rounded mx-auto d-block" alt="...">
  <h1>
    <%= course.title %>
  </h1>

  <p>
    <strong>Description:</strong>
    <%= course.description %>
  </p>

  <p>
    <strong>School:</strong>
    <%= course.school_id %>
  </p>

</div>

app/views/courses/_form.html.erb
<%= form_with(url: school_courses_path) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", school_course_path(@course.school, @course) %> |
  <%= link_to "Back to courses", school_path(@course.school) %>
</div>

app/views/courses/index.html.erb
<h1>Courses</h1>

<div id="courses">
  <% @courses.each do |course| %>
    <%= render course %>
    <p>
      <%= link_to "Show this course", school_course_path(course.school_id, course) %>
    </p>
  <% end %>
</div>

<%= link_to "New course", new_school_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to 'Back', :back %>
</div>

app/views/courses/show.html.erb
<%= link_to "Back to courses", school_path(@course.school) %>
<div class="row">
  <%= render @course %>
</div>
  <div>
    <% if can? :manage, @course %>
      <%= link_to "Edit this course", edit_school_course_path(@course.school, @course) %>
      <%= button_to "Delete this course", school_course_path(@course.school_id), method: :delete %>
    <% end %>
  </div>
<br><br><hr>

<div class="row">
  <div class="row">
    <div class="col-md-10">
      <h4>Batches</h4> 
    </div>
    <% if can? :manage, @course %>
      <div class="col-md-2">
        <%= link_to "New Batch", new_school_course_batch_path(@course.school, @course), class: "btn btn-info" %>
      </div>
    <% end %>
  </div>

  <% @course.batches.each do |batch| %>
    <p><%= link_to batch.name, school_course_batch_path(@course.school, @course, batch) %> </p>
  <% end %>
</div>